---
:host: 127.0.0.1
:port: 4567
:databases_widget: classic
:options:
  :blastn:
    :default:
      :description:
      :attributes:
      - "-task blastn"
      - "-evalue 1e-5"
  :blastp:
    :default:
      :description:
      :attributes:
      - "-evalue 1e-5"
  :blastx:
    :default:
      :description:
      :attributes:
      - "-evalue 1e-5"
  :tblastx:
    :default:
      :description:
      :attributes:
      - "-evalue 1e-5"
  :tblastn:
    :default:
      :description:
      :attributes:
      - "-evalue 1e-5"
:num_threads: 2
:num_jobs: 1
:job_lifetime: 43200
:cloud_share_url: https://share.sequenceserver.com/api/v1/shared-job
:allowed_import_paths: []
:allowed_import_urls: []
:allowed_s3_buckets: []
:allowed_origins:
- http://127.0.0.1:5174
- http://localhost:5174
:api_only: true
:large_result_warning_threshold: 262144000
:optimistic: false
:database_dir: "/Users/kentnf/projects/omicsagent/sequenceserver/data/blast-db"
:bin: "/Users/kentnf/.sequenceserver/ncbi-blast-2.16.0+/bin"
